### ISSUE TITLE
FYI this works with an LED for TOSLINK connection

### ISSUE THREAD

**Issue by sequoia-hope** [mill1000/raspdif#11]
Thank you for this library! I have discovered that if you hook up a red LED and a resistor (I used about 600 ohms) to the output pin and ground, this works for optical audio output.

Other feedback: The instructions for how to make a service provide the service file but not other instructions for what to do with that file. I looked elsewhere and I think I figured it out, but it might just be a couple more lines in the readme to make that complete.

I currently do not have ALSA working properly, so there may be more feedback, but I need to set this aside for the moment. Mostly wanted to report on success with TOSLINK!

**Comment by mill1000** [comment]
Thanks for the feedback! Fun to hear it works with TOSLINK. Never even crossed my mind to try that.

I'll be sure to update the README with your TOSLINK setup and additional systemd information. Maybe I'll update the `make install` target to copy over the file too.
