### ISSUE TITLE
[Help] Double mono

### ISSUE THREAD

**Issue by dmytro-shchurov** [mill1000/raspdif#13]
Greetings, Sir.

I'm going to build a double mono DAC, and to use two isolated S/PDIFs with WM8804s. 
For that I need two signals with inverted data in left/right words for each of them. One signal would send a left channel with data in the first word and an inverted data in the second word. Another signal would send a right channel with data/inverted data words.

There are two options: either to use a 32(and 64)-bits hardware shift register, or to send two S/PDIF signals from Pi.
I prefer to try the second option first.

Thus, I kindly ask you, Sir, to briefly explain where in the code I can invert an opposite channel data bits, and is this theoretically possible to send an absolute synced pulses into two separate channels?

As I understand (I'm a total newbie in a Pi low level programming), you use I2S data out pin GPIO21 for S/PDIF. Is this true?

Any other ideas would be appreciated.

Thank you.

**Comment by mill1000** [comment]
> There are two options: either to use a 32(and 64)-bits hardware shift register, or to send two S/PDIF signals from Pi.
> I prefer to try the second option first.

Unfortunately I don't think it's possible for the Pi to achieve this. The hardware only has a single PCM/I2S peripheral. 
 
> Thus, I kindly ask you, Sir, to briefly explain where in the code I can invert an opposite channel data bits, and is this theoretically possible to send an absolute synced pulses into two separate channels?

Samples are packed into the subframes here:
https://github.com/mill1000/raspdif/blob/f66d98bec2ee97355105c78b9b1e242cac4ea6ca/source/main.c#L282-L288

> As I understand (I'm a total newbie in a Pi low level programming), you use I2S data out pin GPIO21 for S/PDIF. Is this true?

Yes that is true.

> Any other ideas would be appreciated.

This ones a long shot.
The PCM peripheral can be operated as a clock master or clock slave. Theoretically if you had two Pis, one as master and the other as slave, the FIFOs would be unloaded and transmitted in reasonable sync. So the challenged would be to load the FIFOs with synchronized data.

[Snapcast](https://github.com/badaix/snapcast) is project to enable synchronous multiroom audio. So in _theory_, it could deliver synchronized audio streams to both Pis. One Pi could be configured to transmit left samples, the other right samples, from this sync'd stream.

However, I'm making a large assumption about the synchronization ability of Snapcast. My gut feeling is that multi-room audio can tolerate much larger delays (ms?) deviation than you want to achieve with this setup.

**Comment by dmytro-shchurov** [comment]
Thank you very much for the info. One PCM/I2S per CPU is a real showstopper. 

Do you know, which PCM format does BCMxxx SoC use? I mean does it use left/right justified, or i2s format? In opposite to left/right justified one, i2s waits two BCLK ticks before data appears available on DOUT pin. 
So, if I 
1) mix left and right channels bits (0-left, 1-right, 2-left, 3-right, and so on) 
2) configure a transmit mode to left justified
then with a simple hardware trigger I could convert left justified to i2s (during these first two ticks I delay a data for one tick to separate channels)

Do you think, sir, this is possible?

Because two Pis and multiroom seems way more complex solution than several shift registers and few input selectors of the hardware implementation of channel separation. And I'd like to keep all the processing before WM8804 to not introduce an additional jitter.

**Comment by mill1000** [comment]
I think the PCM peripheral is capable of either mode. You can browse the documentation here: https://datasheets.raspberrypi.com/bcm2835/bcm2835-peripherals.pdf

But this project doesn't use the peripheral in a typical mode, but instead as a high speed serializer to clock out the manually encoded data at 2x rate.

**Comment by dmytro-shchurov** [comment]
Good. A lot of keywords that will definitely help me to proceed.

Thank you very much, sir.

**Comment by mill1000** [comment]
Good luck! Thanks for closing the issue.
