### ISSUE TITLE
Compile error on DietPi

### ISSUE THREAD

**Issue by Jimsoft1** [mill1000/raspdif#21]
Hi, trying to compile on DietPi gives me the following errors.  I'm sure it's something I've done wrong or not done!

```
In file included from include/bcm283x/bcm283x.h:24:
include/bcm283x/bcm283x_dma.h:221:1: error: static_assert failed due to requirement 'sizeof(struct dma_control_block_t) == 8 * sizeof(unsigned int)' "dma_control_block_t must be 32 bytes."
static_assert(sizeof(dma_control_block_t) == 8 * sizeof(uint32_t), "dma_control_block_t must be 32 bytes.");
^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/assert.h:143:24: note: expanded from macro 'static_assert'
# define static_assert _Static_assert
                       ^
In file included from source/main.c:11:
In file included from include/bcm283x/bcm283x.h:24:
include/bcm283x/bcm283x_dma.h:223:1: error: static_assert failed due to requirement 'sizeof(struct bcm283x_dma_channel_t) == 9 * sizeof(unsigned int)' "bcm283x_dma_channel_t must be 36 bytes."
static_assert(sizeof(bcm283x_dma_channel_t) == 9 * sizeof(uint32_t), "bcm283x_dma_channel_t must be 36 bytes.");
^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/assert.h:143:24: note: expanded from macro 'static_assert'
# define static_assert _Static_assert
```

**Comment by Jimsoft1** [comment]
OK, I fixed this by cloning the 64 bit branch. Silly me!

**Comment by Jimsoft1** [comment]
OK, I fixed this by cloning the 64 bit branch. Silly me!

**Comment by mill1000** [comment]
Cool. Let me know how that 64-bit build works out for you. It's a bit experimental

**Comment by Jimsoft1** [comment]
Built and installed easily.  Followed your instructions for configuration and it worked first time once I’d built the cable.

One issue is that viewing the output with a scope you can see no data before playback starts but continues transmitting after the song has finished.  If I listen on headphones some noise can be heard after a track has finished (manifests as a very quiet tone of varying frequency).  This may actually help my setup as the old Marantz AV amp I'm using takes a while to start playing when data begins thus preventing it missing the first half a second on subsequent tracks if there's no lead in.  I hope that makes sense and may be linked to https://github.com/mill1000/raspdif/issues/4

Thanks for your excellent work, it's very useable as it is.

**Comment by mill1000** [comment]
Try the `--no-keep-alive` option. Let me know if the noise goes away.
