### ISSUE TITLE
Alternative PINs for SPDIF out

### ISSUE THREAD

**Issue by marcoalexcampos0** [mill1000/raspdif#9]
Hi,

I have several RPi ranging from Model A Rev2, B Rev 1, B+, etc. that I'd like to use for this project.

But those that have the GPIO with only 26 PINs don't have the 40th PIN to connect the SPDIF interface, so I started to look around.

For Model B Rev 1, you can use the pin 13 for SPDIF and 14 for ground (tested! :) )
For Model A/B Rev 2 you don't have a PIN, but I've traced the processor pin to PIN 11 on S5 connector (camera), but was not able to test it so far, and probably is not an easy place to solder.

So my question is: Is there any other PIN that can be used for this purpose and we'll change the code before compiling, or have an option to specify a different PIN when you invoke the program?

Thank you.
Marco Campos

**Comment by mill1000** [comment]
Hi Marco,

The PCM peripheral can only output on GPIO21 or GPIO31, but raspdif currently uses GPIO21. You will have to edit the code to use GPIO31.

Based on this diagram
![image](https://user-images.githubusercontent.com/6924622/105524756-51631180-5c9d-11eb-8f51-028bcb4b388e.png)

As you found, Pin 13 is correct for RPi B Rev 1, although other diagrams disagree that GPIO21 is located on Pin 13.

Unfortunately it does not look like GPIO31 is readily available on the GPIO header. If you have links to schematics for your earlier boards I could help you find the pins.

**Comment by marcoalexcampos0** [comment]
Thank you very much for the input. I will test the track 11 on the CAM connector for now, since the ping 40 on the RPi 1 B+ and the 13 on the "original" RPi B I've confirmed that work.

**Comment by marcoalexcampos0** [comment]
Just confirmed that on the RPi 1 Rev 2, the pin 11 of S5 (camera connector) works as SPDIF output (GPIO21).
A bit difficult to solder there, but works! :)

**Comment by marcoalexcampos0** [comment]
The picture to show the pin:

![0J4942 1200 - GPIO 21 - PIN 11 of S5 - RPi 1 Rev 2 - SPDIF Output](https://user-images.githubusercontent.com/58051181/105716915-63e87f80-5f17-11eb-8ae2-ab748ce09f56.jpg)

**Comment by marcoalexcampos0** [comment]
Now I will test the GPIO31 on PIN 6 of P5 connector.

Should I just change the "21" on main.c to "31" or do I need to change more things?

  // Configure GPIO 21 as PCM DOUT via AF0
  gpio_configuration_t gpioConfig;
  gpioConfig.eventDetect = gpio_event_detect_none;
  gpioConfig.function = gpio_function_af0;
  gpioConfig.pull = gpio_pull_no_change;
  gpioConfigureMask(1 << 31 , &gpioConfig);

![GPIO31 - P5 6 - RPi 1 Rev 2](https://user-images.githubusercontent.com/58051181/105718840-94311d80-5f19-11eb-96cc-e3ede76abe48.jpg)

![p5-header21](https://user-images.githubusercontent.com/58051181/105719073-ce9aba80-5f19-11eb-8f1b-6434a33079d7.jpg)

**Comment by mill1000** [comment]
You should change 21 to 31 and `gpio_function_af0` to `gpio_function_af2`

For this application we are using the PCM_DOUT pin

![image](https://user-images.githubusercontent.com/6924622/105864320-099afd80-5faf-11eb-92a0-b5b65bfb0dfb.png)

**Comment by marcoalexcampos0** [comment]
Tucker,

Thank you very much. I've recompiled with af2 and I can confirm that PIN 6 on P5 (GPIO31) on a RPi A Rev 2, works! :)

With this last test we can confirm that your code supports ALL Raspberry Pi boards :) even those older models that most people have put aside.

Let me know if I can be of any assistance. 

Cheers,
Marco.

**Comment by mill1000** [comment]
Marco,

That's great. Thanks for running this through. I'll make a point to update the README with your discoveries.

**Comment by marcoalexcampos0** [comment]
Let me know if I can be of assistance on any other subject. :)

**Comment by mill1000** [comment]
Thanks again Marco. I've updated the README with some information about GPIO31 and the P5 header.

**Comment by marcoalexcampos0** [comment]
Glad to be useful. ;) Thank you for your great work.
